development: 
  servicePort: 8983
  serviceProxyAddress: http://libserver4.yale.edu:8983/solr/
  serviceAddress: http://libserver4.yale.edu:8983
  serviceType: solr
test: 
  servicePort: 8983
  serviceProxyAddress: 
  serviceAddress: http://localhost:8983/solr/
  serviceType: solr
production: 
  servicePort: 8983
  serviceProxyAddress:
  serviceAddress: http://localhost:8983/solr/
  serviceType: solr
